name: generate-cred

on:
  pull_request: []
  schedule:
    # Every 6 hours
    - cron: 0 */6 * * *

jobs:
  GenerateCred:
    name: Generate Cred
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Run SourceCred
        uses: vsoch/cred-action@wip-discord
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          SOURCECRED_DISCORD_TOKEN: ${{ secrets.SOURCECRED_DISCORD_TOKEN }}
        with:
          weights: weights.json
          project: '@metagame'
          project-file: project.json
          branch-against: master
          automated: true
